"""
PlanningHint data model.

The sole structured error/type context source consumed by GraphPlanner.
Generated by the runtime layer (NodeRunner / GraphController) from raw
exceptions, schema mismatches, and adapter information.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class PlanningHint:
    """
    Curated planning hint — the only error/type context that GraphPlanner
    is allowed to consume.  Raw exception stacks, manifest.json fields,
    and NormalizationRecord data must NOT be passed to the planner directly.
    """
    error_class: Optional[str] = None          # RuntimeErrorClass value
    error_code: Optional[str] = None           # ErrorCode value
    compatibility_level: Optional[str] = None  # CompatibilityLevel value
    adapter_info: Optional[str] = None         # adapter information summary
    suggested_fix: Optional[str] = None        # fix suggestion
    type_mismatch_detail: Optional[str] = None # type mismatch details
    envelope_targets: List[str] = field(default_factory=list)  # skills supporting envelope
    schema_version: str = "1.0.0"
